### ISSUE TITLE
Add build-time mechanism for loading a set of token replacements, adding them to the lexicon, and serializing them

### ISSUE THREAD

**Issue by apendleton** [mapbox/fuzzy-phrase#53]
When we build indexes, we’ll need a way to represent token replacements and bake them into our datastructure. What that will entail:

- [x] add a function to FuzzyPhraseSetBuilder that’s called like `load_token_replacements` (or something similar); it will accept a list of from/to replacement pairs (a vector of tuples, or vector of structs if we want to name `from` and `to`), and will do two things with them: store them someplace on the structure so that they can be written out later (will require a new field), and add both the from and the to words to the working dictionary so that they both get assigned temporary IDs
- [x] modify the FuzzyPhraseSetMetadata struct so that it has a place to put the token replacements, which we’ll bake into the config file we write for each build — this will mean adding a field, and adding a default value for that field (probably just an empty list of replacements); for legibility, let’s make this a string→string mapping rather than an ID→ID mapping
- [x] modify the finish function so that it writes out the token replacements to its config file

**Comment by apendleton** [comment]
Actually let's think about `word_replacement` instead of `token_replacement` since `token` is overloaded and we've been avoiding it in this library so far

**Comment by boblannon** [comment]
Is there any reason for the `load_word_replacements` logic to happen outside of `FuzzyPhraseSetBuilder::new`?  If we're not able to assume that it happens at instantiation, then we'd need to complicate the `insert` method to behave differently, depending on whether or not `load_word_replacements` had been called first.

**Comment by apendleton** [comment]
Yeah honestly I proposed doing it as a separate function out of laziness, so we don't have to change all the calls in the existing tests to have an additional param. I don't feel strongly either way.

For what it's worth, though, I'm not sure what the implications for `insert` are -- as currently proposed, we're not changing anything about `insert`.

**Comment by boblannon** [comment]
> For what it's worth, though, I'm not sure what the implications for insert are -- as currently proposed, we're not changing anything about insert.

Yeah, i misunderstood when i wrote that.  still sinking back into the code :)
